<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE puppets [
        <!ELEMENT puppets (puppet)*>
        <!ELEMENT puppet (id, img, name, size, price, summary, description)>
        <!ATTLIST puppet type CDATA #REQUIRED>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT img (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT size (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT summary (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        ]>
<puppets>
    <puppet type="marionette">
        <id>MR0001</id>
        <img>/mathiafl/clone/test/images/ballerinaMarionette.jpg</img>
        <name>Ballerina Nina</name>
        <size>Medium</size>
        <price>€130.5</price>
        <summary>Ballerina marionette with glass fiber threading and wighted shoes</summary>
        <description>Fits for all ages but most suited for girls, this ballerina will jump hop and skip into your heart
        </description>
    </puppet>
    <puppet type="rodPuppet">
        <id>RP0001</id>
        <img>/mathiafl/clone/test/images/alienRod.jpg</img>
        <name>Alien</name>
        <size>Small</size>
        <price>€75.90</price>
        <summary>This is a sci-fi favourite and will dissolve all your reservations against puppets</summary>
        <description>As seen in Alien, Aliens, Alien 3, Alien: Ressurection, Alien vs. Predator, Alien vs. Predator:
            Requiem
        </description>
    </puppet>
    <puppet type="rodPuppet">
        <id>RP0002</id>
        <img>/mathiafl/clone/test/images/chutuluRod.jpg</img>
        <name>Chutulu</name>
        <size>Gargantuan</size>
        <price>€199999.90</price>
        <summary>The darklord, and great saviour of our current excistance!</summary>
        <description>All hail Chutulu</description>
    </puppet>
    <puppet type="shadowPuppet">
        <id>SP0001</id>
        <img>/mathiafl/clone/test/images/courtingShadow.jpg</img>
        <name>Jane &amp; James</name>
        <size>Medium</size>
        <price>€160.5</price>
        <summary>How about some sexy shadow-play for your love before ending the night in some hot handpuppeteering?
        </summary>
        <description>Act out the story of two lovers in the shadows, using light.</description>
    </puppet>
    <puppet type="handPuppet">
        <id>HP0001</id>
        <img>/mathiafl/clone/test/images/earnieHand.JPG</img>
        <name>Earnie</name>
        <size>Medium</size>
        <price>€99.85</price>
        <summary>Something about him beeing suer famous from Sesame Street</summary>
        <description>If you pay double amount his friend Alf may also join him in his journey.</description>
    </puppet>
    <puppet type="handPuppet">
        <id>HP0002</id>
        <img>/mathiafl/clone/test/images/elmoHand.jpg</img>
        <name>Elmo!</name>
        <size>Medium</size>
        <price>€999.85</price>
        <summary>Something about him beeing suer famous from Sesame Street</summary>
        <description>This guy dosen't atleast eat your cookies</description>
    </puppet>
    <puppet type="animatronics">
        <id>AN0001</id>
        <img>/mathiafl/clone/test/images/etAnima.jpg</img>
        <name>E.T</name>
        <size>Huge</size>
        <price>€9999.85</price>
        <summary>This stranded alien is looking for a home</summary>
        <description>NB! be careful of having your phone close to him or you may see some expensive long distance calls
            on your bill.
        </description>
    </puppet>
</puppets>